#!/bin/bash
clear
echo "###################################################";
echo "############ Deleting temporary files #############";
find -name "*~" > mrclean_tmp.tmp;
find -name "#*#" >> mrclean_tmp.tmp;
find -name "*.o" >> mrclean_tmp.tmp;
find -name "vgcore.*" >> mrclean_tmp.tmp;
find -name "libmy.a" >> mrclean_tmp.tmp;
find -name "a.out" >> mrclean_tmp.tmp;
find -name "*.hi" >> mrclean_tmp.tmp;
find -name "*.a" >> mrclean_tmp.tmp;
find -name "*.so" >> mrclean_tmp.tmp;
find -name "*~" -delete;
find -name "#*#" -delete;
find -name "*.o" -delete;
find -name "*.hi" -delete;
find -name "*.a" -delete;
find -name "*.so" -delete;
find -name "vgcore.*" -delete;
find -name "libmy.a" -delete;
find -name "a.out" -delete;
echo "###################################################";
cat mrclean_tmp.tmp;
rm mrclean_tmp.tmp;
echo "###################################################";
echo ""
echo -e "\e[32mDone\e[0m"